run	:main.o graph.o heap.o util.o
	g++ -o run -std=c++11 main.o graph.o heap.o util.o

main.o	:main.cpp main.h graph.h heap.h util.h
	g++ -c -std=c++11 main.cpp

graph.o	:graph.cpp main.h graph.h heap.h util.h
	g++ -c -std=c++11 graph.cpp


heap.o	:heap.cpp main.h graph.h heap.h util.h
	g++ -c -std=c++11 heap.cpp

util.o	:util.cpp main.h graph.h heap.h util.h
	g++ -c -std=c++11 util.cpp

clean	:
	rm *.o 

cleanAll	:
	rm *.o run
